### ISSUE TITLE
Agent based model examples

### ISSUE THREAD

**Issue by jpfairbanks** [jpfairbanks/SemanticModels.jl#106]
We need a few examples of agent based models so that we have some diversity away from ODEProblem.

**Comment by jpfairbanks** [comment]
One thing we might want to do with agent based models is have an extractor/context that identifies the Finite State Machine of the agents by static analysis or running the code. Then we can talk about transforming models by changing the FSM which is a higher level of representation than the code level.

@mehalter, What is the right way to construct our ABM so that the agents are simple algebraic structures like FSM or Nondeterministic Automata?

**Comment by mehalter** [comment]
@jpfairbanks and I discussed this on the phone earlier today, and currently in the `example/agentbased.jl` model example and the `bin/agentgraft.jl` SemanticModels example of manipulating the ABM model is programmed how you would define the changes mathematically as a FSM/NFA, where you add the state, add the new state transitions, and modify the old state transitions. This makes it pretty complicated to modify. The example in the `agentgraft.jl` is a pretty simple example, but takes a good amount of code and knowledge of the codes current state machine to change.

I think a simpler and more intuitive way to approach this would be to be able to export subexpressions as metagraphs of states and functions, edit the graph (like add new states and define the changes in transitions/functions as edges), then have Semantic models convert the new metagraph to the correct model and put it back where it went before instead of think about the algebraic changes that need to be made to the FSM definition.

**Comment by jpfairbanks** [comment]
Yeah I think this is on the right track

**Comment by jpfairbanks** [comment]
This is closed in #107
