### ISSUE TITLE
Finding concepts that need definition

### ISSUE THREAD

**Issue by jpfairbanks** [jpfairbanks/SemanticModels.jl#13]
We need a set of phrases that need definitions/expository text. and the hyperlinks that define them.

**Comment by jpfairbanks** [comment]
Possible down stream use of this, ask UW researchers to give us all the hits for these terms.

**Comment by crherlihy** [comment]
I pushed v1 of this to the cookbook_definitions branch; still have 2 more sections to go through in cookbook and definitions to fill in. There are dupes (of phrases) across sections because was sort anticipating a future use case where we need n-gram level labels. Next stage will be to review relevant academic papers and fill in DOIs and then find supporting paragraphs/definitions in the papers referenced. 

TODOS:
- Complete phrase selection (e.g., cover all sections of epicookbook)
- Fill in all phrase definitions with web/wikipedia links and text
- Find supporting academic papers, and include DOIs and text.

**Comment by jpfairbanks** [comment]
LGTM by the end of the week.

**Comment by jpfairbanks** [comment]
We can work with the web definitions for now. Lets put the academic defs on the backburner.
