### ISSUE TITLE
Examples that use LsqFit need to install it.

### ISSUE THREAD

**Issue by jpfairbanks** [jpfairbanks/SemanticModels.jl#153]
For all the statistics examples they need to include this snippet at the top.

```julia
try 
    using LsqFit
catch
using Pkg
Pkg.activate("Algebra")
Pkg.instantiate()
Pkg.precompile()
using LsqFit
end
```

**Comment by jpfairbanks** [comment]
This worked for workflows
```julia
try 
    using LsqFit
    using Plots
catch
    using Pkg
    Pkg.activate("Algebra")
    Pkg.add(["LsqFit", "Plots"])
    Pkg.instantiate()
    Pkg.status()
end
    
using LsqFit
using Plots 
```

**Comment by jpfairbanks** [comment]
This needs to be added to /test/*.jl too.

**Comment by mehalter** [comment]
These dependencies are being handled with docker. Should we assume if they are using docker they have them, and if they are not using docker then people can handle adding those dependencies on their own?

Also I disagree with them being added to test/*.jl because those are run when you do the julia test function and those dependencies should be handled in the Project.toml

So depending on what assumptions we make for the example side of things, I think honestly we can assume people are using the docker image to run the examples and if they aren't then they can handle installing and building their own Julia environment instead of us installing packages into their environment. It seems fishy/hacky/unsecure from an outsiders point of view especially when literally any code can be accepted into the Julia official repositories

**Comment by jpfairbanks** [comment]
Yeah i agree. Let’s install the deps into the docker container so that they just work and then add a note in the examples folder that lists the dependencies so that a non docker user can install them manually before running the notebooks.

Then we cover both bases without a hack
