### ISSUE TITLE
Pitt Modeling the World's systems conference.

### ISSUE THREAD

**Issue by jpfairbanks** [jpfairbanks/SemanticModels.jl#19]
We should work towards this Feb 1 deadline for an abstract at this conference. http://pittmodelingconference.sci.pitt.edu/call-for-papers/. It will be in DC and hosted by Paul Cohen, who is leading another ASKE team.

**Comment by crherlihy** [comment]
I c/p their LaTeX template and sent overleaf invitations to everyone.

**Comment by jpfairbanks** [comment]
The deadline was moved two weeks back so we have until Feb 14. I think we can include 
- [ ] Intro
  - [ ] Related work
  - [ ] Contributions
- [ ] theory.md
- [ ] Model modification example (perturbation of SIR)
- [ ] Grafting Example
  - [ ] extraction (show the rules and the graphs)
  - [ ] reasoning (example from docs)
  - [ ] generation (some runtime numbers to show it isn't slow)
- [ ] Conclusions: semantic modeling frameworks can help scientists integrate and modify complex models. We introduce a theoretical framework for these modeling tasks and describe a software system for augmenting scientific thinking through automated knowledge extraction.

**Comment by infvie** [comment]
# Overleaf
## Motivation
 - "This is due in part to the fact that the peer-reviewed publication process incentivizes novelty and (in so doing), indirectly discourages a subset of the collaborative efforts and convergence toward shared norms that might otherwise emerge; the silos that exist across disciplines only serve to exacerbate such challenges, and complicate the task of modeling complex phenomena whose components cross domains." => "Peer reviewed publications incentivize novelty which indirectly obfuscates convergence toward shared norms that might otherwise emerge. Accompanying the current barriers between domains, this lack of coherence exacerbates such challenges and the task of modeling inter-disciplinary phenomena"
 - "In addition, the nature of scientific inquiry often lends itself to highly tailored, procedural scriptsthat are primarily intended to produce and extract results, while objectives such as modularity andthe inclusion of relevant semantic information via the type system,  and/or in comments,  take abackseat." => "The nature of scientific inquiry leads to highly restrictive, disposable scripts which display a distinct insufficiency of modularity, comments, and essential semantic information. "
## Significance
-  I think a justification of why julia could make this a much stronger part (mainly type system) - I think @jpfairbanks would be the best for this
## Overall
 - I think that 4.1 could easily be merged with section 3
 - I dont think the ologs section adds to this paper, but its diagram can be kept
 - I think that the code can be replaced by the semancticmodelsin10min.ipynb

**Comment by jpfairbanks** [comment]
re: Significance

1. Cite this julia paper: https://epubs.siam.org/doi/10.1137/141000671?mobileUi=0
2. Most effort in analysis of programs is either in Functional Languages such as ML and Haskell, or in low level languages such as C/C++. However, scientists write in languages like Python, R, Matlab, and Julia. These languages have the flexibility and productivity that scientists prefer but are difficult to analyze with static analysis tool.
3. Julia Combines the dynamic productivity of a high level language with the numerical performance of a high performance language. This is possible because Julia is designed to be easy to analyze by a Just In Time (JIT) compiler. 
4. Key elements of this design is a robust and capable type system that programmers can use in coordination with multiple dispatch. Programs that behave like statically typed programs written in high performance languages can be analyzed by the compiler and lead to efficient executable code as generated and optimized by LLVM. 
4. We leverage this design by encoding information about model semantics into the type system and using the Julia type inference implementation to let the Julia compiler manipulate those model semantics.
5. Julia is the only language that has a sophisticated type system that is commonly used in scientific computing.

**Comment by crherlihy** [comment]
We submitted on 2/15/19. Will keep this issue open for future revisions and etc.

**Comment by jpfairbanks** [comment]
PC feedback is over the event horizon of April 1st, so I'll close this and open a new issue with a checklist for referee comments once we hear back from the PC.

**Comment by jpfairbanks** [comment]
Here is the final version: [ASKE_MWS19_final.pdf](https://github.com/jpfairbanks/SemanticModels.jl/files/3087852/ASKE_MWS19_final.pdf)
