### ISSUE TITLE
AUTOMATES Definitions from Source Comments

### ISSUE THREAD

**Issue by scottagt** [jpfairbanks/SemanticModels.jl#42]
- Review and analyze several Julia source files / notebooks from EpiRecipes cookbook
- Determine any additional AUTOMATES extraction rules that could be useful to extracting concepts for potential inclusion in knowledge graphs

**Comment by scottagt** [comment]
Scripts from: https://github.com/jpfairbanks/epicookbook/tree/master/updatedJulia

**Comment by jpfairbanks** [comment]
> Read all the function parameters in the file

Do you mean documentation strings/comments? Or are you referring to the things pulled out by cassette?

**Comment by scottagt** [comment]
@jpfairbanks Just now seeing this. Yes, was referring to any lines that begin with a pound sign. Oh no, not referring to cassette. Also, I mentioned I was going to work on this one next yesterday having finished another issue up. Did you mean to close it?

**Comment by scottagt** [comment]
@jpfairbanks I found these recommendations for documenting source code in Julia including defining parameters: https://docs.julialang.org/en/v1/manual/documentation/#Documentation-1

If we expect to be working with code that is documented following those stylistic conventions then it may be worth writing more code-focused extraction rules with them.

Another area of interest could be in extracting phenomena declared within a module and outside of functions. So for example:

```
module MyModule
using Lib

using BigLib: thing1, thing2

import Base.show

export MyType, foo

struct MyType
    x
end

bar(x) = 2x
foo(a::MyType) = bar(a.x) + 1

show(io::IO, a::MyType) = print(io, "MyType $(a.x)")
end
```
where we could extract phenomena like exports, structs names, libraries used. Here's a good place where we can again track in comments when there are things that are mentioned in comments.

We could use regex here (which is good when you don't have access to trained models or a Julia language parser). I haven't worked with Cassette.jl just yet. Does anyone know if we could use it to parse Julia scripts and then loop through a list of parsed elements? If so, we could do that and avoid regex.  

@crherlihy looping you in too since we've been talking about it recently :)

**Comment by jpfairbanks** [comment]
> We could use regex here (which is good when you don't have access to trained models or a Julia language parser). I haven't worked with Cassette.jl just yet. Does anyone know if we could use it to parse Julia scripts and then loop through a list of parsed elements? If so, we could do that and avoid regex.

`/bin/extract.jl` uses the library function `Base.Meta.parse` to extract the same AST that the julia compiler gets and then extracts stuff using hand written rules (that christine and I came up with). Rule based extraction is very effective on source code, because the semantics of julia code are precisely defined.

**Comment by jpfairbanks** [comment]
`src/parsers.jl` is the library that `bin/extract.jl` uses to do the parsing part so you could add more rules in there.

**Comment by crherlihy** [comment]
@scottagt , @jpfairbanks I'm going through open issues as we start the next phase of work, and just wanted to add an observation here from the process I went to trying to manually create edges between the vertices we receive by parsing the epicookbook markdown, and the vertices we receive by parsing the associated code. 

The result of the pre-automates matching of (comments) text to code (e.g., variable declarations), for example, means that the vertices and associated definitions edges we get out of the automates parser often connect (natural language-ish) text to code, rather than text to text. This makes manual edge insertion somewhat circular, since we want to connect domain to code but are generally (at best) able to connect code to code. 

I understand the motivation for the check (e.g., to ensure that what we parse is relevant). I think if we stick with this logic though, it should be used to help focus attention on the sentences within the markdown, rather than the text-> code relationship.

**Comment by scottagt** [comment]
@crherlihy Good points; I should clarify the check (or that particular motivation) is just one any number that could be done/had. In the context of linking variables to code phenomena, specifically function names and function parameters, it's one thing that could be done but not the only thing. And so agree, if there are other kinds of relationships that we know ahead of time we want to do extraction for, for specific purposes, we should totally do those in beneficials ways to graph construction.
